version: '3'

services:
  web:
      build:
        context: ./Pranav
        dockerfile: Dockerfile
      command: python __init__.py
      ports:
        - 3000:3000
      depends_on:
        - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flaskJWT
